### ISSUE TITLE
Display annotation progress for each dataset

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#14]
Think through a metric for annotation completion; map the metric to badges for each dataset completion level? Is there a maturity model for dataset annotations?

**Comment by milen-sage** [comment]
Need to aggregate all metadata across all manifests in a given projects in a single dataframe.

**Comment by xdoan** [comment]
Some wanted features: and work that would have to be done to implement them:
1. Display validated and submitted manifests and unsubmitted but necessary manifests, possibly with complete/imcomplete or % completeness
This would require knowing a) what the minimum "completeness" for going public is, e.g. clinical, biospecimen to show on legends when they are blank, b) having the HTAN IDs check so that the dependencies are followed as more data is submitted (e.g. as more assays are submitted, making sure their parent biospec/clinical ID metadata is also submitted)
2. Display the metadata version number/out-of-dated-ness
This would require versioning of metadata and some way to check that, or some function to check if its out of date, or some other mechanism that can then be displayed.
3. Display a table of info per folder with metadata version, if its outs of date, link to manifest, info about number of files/HTAN IDs, etc
This would require the function that aggregates all the manifests in a project in one dataframe so I can run summary stats etc on them. 

Additionally:

4. If and when we add the "save" a new feature to display In Progress % complete of required fields 
but that circles back to how it is difficult to know the number of required fields as it can change with conditional logic. I could imagine that every time they press "validate" it would update the % and if it goes to a lower number explaining why? 

@milen-sage @BrunoGrandePhD any additional thoughts?

**Comment by milen-sage** [comment]
@xdoan these make sense to me. 

4. Is indeed non-trivial: given dependency between column values and required cells to fill in the manifest may become less complete the more data is provided (e.g. biospecimen type is changed from cell to analyte, implying 10 other columns are required). However, we can indicate that to the user as part of a breakdown of metadata completion for unconditionally required columns and conditionally required columns.

3. Some options to consider here: 
- would you rather have the backend to run the validation, on each manifest and return the errors/warnings for each manifest along with the aggregated manifests (in case you need to pull some data from them); and the frontend then summarizes the errors and visualizes the results
- or would you rather have the aggregated dataframes and call the validation routines on the backend for each dataframe

2. Yes, this is related to something we've been discussing also w/ @BrunoGrandePhD: how do we handle schema updates  and out of date annotations more gracefully. Needs more fleshing out, but I think we still make progress on the dashboard given 4 and 3

1. Yes, this is related to how do we know what are the dependencies between different metadata/data types (i.e. schema components) and how do we join existing manifests together using these dependencies. We can assume the schema reflects the minimum dependent components that need to be completed before a dataset can go public (e.g. if scRNA-seq level 1 dataset is submitted and the schema indicates scRNA-seq level 1 requires Biospecimen data and Biospecimen data requires Clinical Data Tier 1 and that requires Demographics, Family History) than the minimal completeness for this dataset to go public is the presence of valid manifests for scRNA-seq level 1, Biospecimen, Demographics, Family History. Schematic can return that dependency chain. To start off, we can assume that for the dataset to be complete each of these manifest is valid. As a next layer, we can add joining the manifests based on the data contributor provided IDs and returning any errors for missing data for an ID; the code doing the joins lives in schematic since there is an automated generic way to do the joins given the schema component dependencies.

**Comment by xdoan** [comment]
It would definitely be good to create separate issues for them! This can be an overview to help orient us to the topic/scope.  

1. This is even related to a higher level question of what makes up "complete" metadata for going public or the portal and how to communicate that visually, not just the backend functionality required to make that happen. I agree for simple purposes I can prototype with just submitted Clinical, Biospec, and 1 assay metadata template as "complete" but it won't make much sense for HTAN projects as they grow in complexity. 

3. what do you mean by validation?

**Comment by milen-sage** [comment]
If you mean validation in 3., that's just metadata validation: each dataset manifest dataframe contains metadata that we want to evaluate w.r.t. the schema, using the validation methods in schematic. For now that's just manifest by manifest validation w/o looking at linkages between data type components.

**Comment by xdoan** [comment]
so ^validation was in regards to validating saved In-Progress which is a more complex problem. 

The idea is to have overall/summary metrics (how many in progress templates, which necessary templates are missing, how many complete templates, etc)

**Comment by BrunoGrandePhD** [comment]
@xdoan: Thanks for kicking off this discussion! I'm happy to hop on a call anytime to discuss this further if you prefer brainstorming features or implementation details that way. 

Here are some of my thoughts:

- **Re: Percent completeness.** Could we display a range of percent-completeness given the metadata that's been provided so far? This seems more intuitive for the users. I'm imagining there's a way of using the data model graph to calculate a lower and upper bound on the number of required fields. The main challenge with this approach is implementing an efficient algorithm for traversing the graph. We could discuss how to implement this if you think the improved UX is worth it. 
- **Re: Out-of-dateness.** We can include the version of the data model used to generate the manifest template in a fixed/protected column of the template. Determining out-of-dateness could either be done using the version numbers (rough but easy to implement) or by re-validating the manifest using schematic (precise but computationally intensive if this needs to be done every time the data model is updated). This out-of-dateness should ideally be tracked in an annotation of the file so that the information can also be used by an admin-facing dashboard. 
- **Re: Manifest states.** What are the different states for manifests? Here are some ideas: `Valid`, `Invalid (out-of-date)`, `Invalid (incomplete)`, and `Not started`. I'm assuming that out-of-dateness is only important if it leads to validation errors. In other words, it's not important to track a `Valid (Out-of-date)` state, which most metadata would probably end up with and might confuse users on whether they need to update "valid but out-of-date" metadata. 
- **Re: Out-of-sync annotations.** This would be more important for the admin-facing dashboard, but I don't see any harm in informing users of out-of-sync annotations. Specifically, I'm thinking of ensuring that Synapse annotations are consistent with the corresponding values in the manifest. If discrepancies arise for whatever reason, that dataset file should be marked as "out-of-sync", ideally with specific information as to why (_e.g._ which annotation/attribute is affected).

**Comment by BrunoGrandePhD** [comment]
I think so 🤔
