### ISSUE TITLE
not all templates are showing up in dataset selection dropdown

### ISSUE THREAD

**Issue by inodb** [Sage-Bionetworks/data_curator#149]
When I try to use https://www.synapse.org/#!Wiki:syn20681266/ENTITY

I don't e.g. see `scRNA-seq Level 4` in the dropdown. Just Level 1:

<img width="540" alt="Screen Shot 2021-04-10 at 9 55 47 AM" src="https://user-images.githubusercontent.com/1334004/114272170-0bd3fc00-99e3-11eb-8d44-d4d489b782b8.png">

**Comment by milen-sage** [comment]
@inodb - thanks for spotting. I was just bumping into a similar issue myself. 

In the latest codebase update from Fri, we have erroneously not pulled in the latest HTAN schema; it accidentally uses and old one...

Tagging @sujaypatil96 -  highest priority fix:
- update DC app HTAN schema to use latest [one](https://github.com/Sage-Bionetworks/schematic/blob/main/data/schema_org_schemas/HTAN.jsonld) (note this schema is on 'main' branch; need to update develop)
- confirm the set of metadata templates in the DC app contains all the [components](https://github.com/ncihtan/HTAN-data-curator/blob/shiny-server-1.2.1.rc1/www/config.json) supported by the latest HTAN schema

**Comment by sujaypatil96** [comment]
Thanks for catching this @inodb. This happened because we hadn't updated the HTAN data model to it's [latest](https://github.com/Sage-Bionetworks/schematic/blob/main/data/schema_org_schemas/HTAN.jsonld) version. The file ([config.json](https://github.com/ncihtan/HTAN-data-curator/blob/shiny-server-1.2.1.rc1/www/config.json)) that controls what items are in the template drop down wasn't updated either.

To fix this, we will update the default branches on both `schematic` and the `Data Curator App`'s end to ensure that this doesn't come up again.

It has been fixed for now. You can see all expected templates in the drop down.
<img width="587" alt="Screen Shot 2021-04-12 at 12 59 51 AM" src="https://user-images.githubusercontent.com/20239224/114360931-717ed000-9b2a-11eb-878c-98d362563a01.png">

For reference, you can also use this link to access the Data Curator App @inodb: https://shinypro.synapse.org/users/spatil/HTAN-prod/

**Comment by inodb** [comment]
Awesome - thanks for the quick fix @milen-sage and @sujaypatil96 !

**Comment by sujaypatil96** [comment]
this issue was resolved based on issue #154.
