### ISSUE TITLE
Upon encountering validation error, provide index of error 

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/data_curator#169]
One of our users uploaded a 200 row manifest with many columns, and the validation report shows the following: 

<img width="1515" alt="Screen Shot 2021-05-25 at 4 30 48 PM" src="https://user-images.githubusercontent.com/20408008/119581602-b9268780-bd77-11eb-8e23-69bd2975cc35.png">

It would be helpful if it provided the index, or at least the row, of the error, so that the user can find the value quickly.

**Comment by rrchai** [comment]
Yeah, the reason we removed row index was because we tried to avoid the confusion between google sheet row index and `datatable` row index. But I agree with you, if filled manifest has a lot of rows and just a couple of wrong values , it will be hard for users to locate the invalid values. 

So I think we will make following changes:

- [ ] add the row index back into error table and I believe the index will match the google sheet index
- [ ] add the row number back into preview table, but index here will start with `2` instead of `1` to avoid confusion. 
- [ ] add search function in each column, so user can search invalid values in preview table as well.

@allaway and @milen-sage, do you think this will be helpful?

**Comment by milen-sage** [comment]
Yes, agreed @rrchai,  given the row index now match Google sheet's indexing, displaying this info would be helpful for the user.

> add search function at the top of each column, so user can search invalid values each column in preview table as well.

This^ would be useful but if it takes more than a couple of hours to implement let's prioritize w.r.t. other work on the DC app.

**Comment by allaway** [comment]
Thanks, both! That makes a lot of sense. 

@milen-sage  - thankfully, simple search is very easy to implement in `reactable` or `DT`: https://shiny.rstudio.com/gallery/nhl-play-by-play.html
