### ISSUE TITLE
Disconnect during submission

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#192]
Update from Clarisse on Thursday 9/16:

I started making my way through the folder of outstanding HTAPP metadata tables, trying to submit them following the recent DCA fixes. I was able to submit a couple, but am still running into disconnect errors for many others. 

**Biospecimen**

- Submitted: [PML](https://www.synapse.org/#!Synapse:syn26174519)
- Failed after clicking submit: [lung](https://drive.google.com/file/d/1Bo-nvFs6ZDjqaHd_bCmH2crcxnQ2KW7P/view?usp=sharing)
- Failed after clicking submit: [ovarian](https://drive.google.com/file/d/1DapQw9a62znpDxxMaCT5SfBdjXjUkatH/view?usp=sharing)

**ScRNAseq Level 1**

- Failed after clicking submit: [PML](https://drive.google.com/file/d/18B48uA_YevC6E7CK1LdBY06iPMLG6Cl5/view?usp=sharing)
- Failed after clicking submit: [sarcoma
](https://drive.google.com/file/d/1Ud5UKVgAAtrW146oBZdpYTcoHGAtFQwn/view?usp=sharing)

_Originally posted by @ychae in https://github.com/Sage-Bionetworks/data_curator/issues/190#issuecomment-923175852_

**Comment by rrchai** [comment]
The error associated with this issue:

Warning: Error in py_call_impl: SynapseHTTPError: 400 Client Error: 
Invalid annotation name: 'Intervaloftimebetweenremovalfromthebodyandtissueisplacedinmedia(minutes)'. Annotation names may only contain; letters, numbers, '_' and '.'

Detailed traceback: 
  File "/home/rchai/miniconda3/envs/data_curator_env_oauth/lib/python3.7/site-packages/schematic/store/synapse.py", line 534, in associateMetadataWithFiles
    self.syn.set_annotations(annos)
  File "/home/rchai/miniconda3/envs/data_curator_env_oauth/lib/python3.7/site-packages/synapseclient/client.py", line 1454, in set_annotations
    body=json.dumps(synapseAnnos)))
  File "/home/rchai/miniconda3/envs/data_curator_env_oauth/lib/python3.7/site-packages/synapseclient/client.py", line 3891, in restPUT
    response = self._rest_call('put', uri, body, endpoint, headers, retryPolicy, requests_session, **kwargs)
  File "/home/rchai/miniconda3/envs/data_curator_env_oauth/lib/python3.7/site-packages/synapseclient/client.py", line 3841, in _rest_call [... truncated]

**Comment by milen-sage** [comment]
Let's fix this in schematic: [this line](https://github.com/Sage-Bionetworks/schematic/blob/c5a4814d3c9853e957a9c97400a7ca2d88a4afd9/schematic/store/synapse.py#L510) should be a good place.

**Comment by milen-sage** [comment]
@clarisse-lau @elysekozlowski @nithyav21

In case this problem re-emerges in other settings, HTAPP have added columns to their metadata manifests that are not in the HTAN schema. These column names contain symbols like '(' which are not acceptable (in any reasonable data system) in column names. That causes the error reported above. 

We could resolve by trying to clean column names automatically, this is the fastest solution, but there are many possible ways to break that logic, in general. The next fast solution is cleaning up the manifest columns (either removing extra columns or removing parenthesis from columns). I'll go with the former. We should have this ready to test tomorrow along with fixes related to some of the other issues.

Mid-term, we can surface a more descriptive error, rather than letting the application crash - @ychae could you add an enhancement issue on that?

**Comment by ychae** [comment]
Issue created :)

**Comment by nithyav21** [comment]
Thanks @milen-sage ! Could we save the data from the extra columns with HTAN IDs elsewhere if the plan is to remove the extra columns so the data is not lost?

**Comment by milen-sage** [comment]
@nithyav21  note: we are going with the solution of changing extra column names so that they don't contain characters like '('. We are not removing the columns.
