### ISSUE TITLE
Manifests submitted to same folder when app not refreshed between submissions

### ISSUE THREAD

**Issue by clarisse-lau** [Sage-Bionetworks/data_curator#228]
HTAN Vanderbilt contributor submitted an updated biospecimen manifest, followed by 7 clinical (demographics, diagnosis, etc.) manifests on Nov. 4. She re-selected the appropriate folder and template options from the dropdown menus for each submission, without refreshing the app in between. All manifests were stored in the 'biospecimen' folder as new versions.

Initial biospecimen submission: https://www.synapse.org/#!Synapse:syn25010909.10
Subsequent clinical submissions stored as versions 11-17 of the same Synapse file

**Comment by milen-sage** [comment]
@rrchai could you try replicating? 

@clarisse-lau thanks for filing an issue, the expected behavior is there is no refresh needed.

**Comment by rrchai** [comment]
@clarisse-lau @milen-sage good catch!

The file ID is only updated in the second tab (generating template) in the current code base. So, if the users do not go to the second tab, the folder Id is not updated, which is not expected behavior. 

I have made some changes in pr #230 with some minor improvement related to submission.
