### ISSUE TITLE
Use schematic's REST API in dashboard

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#367]
**Describe the solution you'd like**
Refactor the DCA dashboard code to use schematic's REST API calls instead of python/reticulate.

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by ychae** [comment]
please enumerate the REST API calls

**Comment by afwillia** [comment]
Schematic REST API endpoints:
- /storage/assets/tables
- /model/validate
- /model/component-requirements
- /storage/project/datasets

Synapse REST API calls
-synapse_get (https://rest-docs.synapse.org/rest/GET/entity/id.html)
-synapse_user_profile (https://rest-docs.synapse.org/rest/GET/user/id/certifiedUserPassingRecord.html)

@ychae @milen-sage I'm running into an issue with differences between the synapsePythonClient `get` and my initial wrapper for synapse `get` in data curator. The python client downloads the query to `.synapseCache` while the R version returns a data.frame. I think it's worth discussing the desired output for the R function - whether to mimic the python client's `get` or return a data.frame.

**Comment by milen-sage** [comment]
Let's chat about it during the FAIR Data working session.

**Comment by milen-sage** [comment]
@afwillia meanwhile could you post a pointer to the code around

> my initial wrapper for synapse get in data curato

**Comment by afwillia** [comment]
https://github.com/Sage-Bionetworks/data_curator/blob/5ecf4841381d778ba543cb24b91fcc3164dd2ca9/R/synapse_rest_api.R#L57

and for easy reference here is the relevant [DCA dashboard code](https://github.com/Sage-Bionetworks/data_curator/blob/29c59580268bd19823b8d66c02e4edc6d58537a9/functions/dashboardFuns.R#L26)

**Comment by rrchai** [comment]
To clarify the needs for current dashboard regarding the synapse's `get`:
1. The dashboard code needs the entity metadata (returned object from syanpsePythonClient) to retrieve the information about the manifest
2. The manifest should be downloaded and the downloading path should be able to acquire. So that the dashboard can further read the manifest and retrieve the data type from the "Component" column

@afwillia I tried the current [synapse_rest_api.R](https://github.com/Sage-Bionetworks/data_curator/blob/5ecf4841381d778ba543cb24b91fcc3164dd2ca9/R/synapse_rest_api.R#L57). I really like you have return the metadata as data frame, but it seems like the downloading path is missing.  

I am not sure if it's able to be retrieved from `httr`, but even if not (assuming it has downloaded the entity) we could find the path based on the `fileHandleId` and `synapseId`. Here is the [source code](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/9e64ed73bb18a903b14011f7142cb72959a108c5/synapseclient/core/cache.py#L97) to define the cach directory from python client

**Comment by afwillia** [comment]
@rrchai yes, I didn't realize this until now, but the `datacurator::synapse_get` function only returns the synapse metadata and does not actually download the file. Looking at `syn.get`, the process to actually download the manifest is more complicated than I originally thought. I agree `synapse_get` will need some functionality similar to `syn.get(downloadFile=True)` to make it useful for the dashboard. I'll talk to @milen-sage and some python folks to figure out the best way to access the manifest from S3.

**Comment by afwillia** [comment]
And the best way is to use the schematic rest api manifest/download endpoint

**Comment by ychae** [comment]
https://github.com/Sage-Bionetworks/schematic/pull/859 should unblock

**Comment by afwillia** [comment]
done with this branch!
https://github.com/Sage-Bionetworks/data_curator/tree/schem-api-feat-ui

Had to modify the asset table endpoint to return a csv, so it's dependent on this branch of schematic https://github.com/Sage-Bionetworks/schematic/tree/develop-asset-view-table-csv
