### ISSUE TITLE
Update MC2 DCA instances

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#434]
Staging instance currently crashes.

AC: staging instance no longer crashes and is using latest release versions of DCA and schematic.

**Comment by afwillia** [comment]
@vpchung @brynnz22 Both the [testing](https://sagebio.shinyapps.io/csbc_data_curator-testing/) and [staging](https://sagebio.shinyapps.io/csbc_data_curator-staging/) apps seem to be working for me now. Let me know how they function for you. Also, I noticed there are some versions using `mc2` instead of `cscb` in the URL. We can switch that now if you want, but need to add those URLs to the OAuth client.

**Comment by vpchung** [comment]
Thanks, @afwillia !  Unfortunately, staging still doesn't work for me.  I tried both `*-staging` (can't be found) and `*_staging` (server disconnects).

**Comment by afwillia** [comment]
This was solved by restarting the instance on the shinyapps.io console.
